# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - uses: eskatos/gradle-command-action@v1
      env:
        BLUELITE_UPDATE_TOKEN: ${{ secrets.BLUELITE_UPDATE_TOKEN }}
      with:
        arguments: build Publish.main
#     - name: Build with Gradle
#       run: ./gradlew build
#     - name: apply patches
#       run: gradle PatchApplier.main
#     - name: generate new patches
#       run: gradle PatchGenerator.main
